### ISSUE TITLE
Doghouse static 404

### ISSUE THREAD

**Issue by earlonrails** [tinkerpop/rexster#387]
I am having trouble with the doghouse. Doesn't seem to know about the static assets. There isn't anything in the documentation about building assets or anything. Maybe there are some missing steps.

![screen shot 2015-06-05 at 4 17 17 pm](https://cloud.githubusercontent.com/assets/666467/8016869/62600f34-0b9e-11e5-9c4e-649f7b8f9b90.png)

**Comment by spmallette** [comment]
Are you running it from the Rexster distribution?

http://tinkerpop.com/downloads/rexster/rexster-server-2.6.0.zip

did you build it yourself?

**Comment by earlonrails** [comment]
I built it myself, what steps should I do after `mvn clean install` ?

**Comment by spmallette** [comment]
If you built it yourself, then try running it from the distribution in: `target/rexster-server/target/rexster-server-x.y.z-SNAPSHOT-standalone` where `x.y.z` of course refers to the appropriate version number.

**Comment by earlonrails** [comment]
I tried this from master and 2.5.0, here is me starting it. Maybe there is another step to point the server to the asset path?

```
~/Projects/rexster/rexster-server  🏄  ./target/rexster-server-2.5.0-standalone/bin/rexster.sh --start
[INFO] Application - .:Welcome to Rexster:.
[INFO] RexsterProperties - Using [/Users/kkrauss/Projects/rexster/rexster-server/config/rexster.xml] as configuration source.
[INFO] Application - Rexster is watching [/Users/kkrauss/Projects/rexster/rexster-server/config/rexster.xml] for change.
[INFO] RexsterApplicationGraph - Graph [dota_heroes] - configured with allowable namespace [tp:gremlin]
[INFO] GraphConfigurationContainer - Graph dota_heroes - tinkergraph[vertices:0 edges:0 directory:plocal:/usr/local/Cellar/orientdb/2.0.9/libexec/databases/dota_heroes] loaded
[INFO] HttpReporterConfig - Configured HTTP Metric Reporter.
[INFO] ConsoleReporterConfig - Configured Console Metric Reporter.
[INFO] HttpRexsterServer - HTTP/REST thread pool configuration: kernal[4 / 4] worker[8 / 8]
[INFO] HttpRexsterServer - Using org.glassfish.grizzly.strategies.LeaderFollowerNIOStrategy IOStrategy for HTTP/REST.
[INFO] HttpRexsterServer - Rexster Server running on: [http://localhost:8182]
[INFO] RexProRexsterServer - Using org.glassfish.grizzly.strategies.LeaderFollowerNIOStrategy IOStrategy for RexPro.
[INFO] RexProRexsterServer - RexPro thread pool configuration: kernal[4 / 4] worker[8 / 8]
[INFO] RexProRexsterServer - Rexster configured with no security.
[INFO] RexProRexsterServer - RexPro Server bound to [0.0.0.0:8184]
[INFO] ShutdownManager$ShutdownSocketListener - Bound shutdown socket to /127.0.0.1:8183. Starting listener thread for shutdown requests.
```
Still get the same from above, seems like the assets are in the repo though. 

```
~/Projects/rexster/rexster-server  🏄  find . -name tinkerpop-splash.png -print
./src/main/resources/public/img/tinkerpop-splash.png
./target/classes/public/img/tinkerpop-splash.png
./target/rexster-server-2.5.0-standalone/public/img/tinkerpop-splash.png
```

**Comment by spmallette** [comment]
could just be a pathing issue. please try to `cd` into `target/rexster-server-2.5.0-standalone` and run from there.  i seem to recall `rexster.sh` being a bit particular about the path.  works for me in that fashion.

**Comment by earlonrails** [comment]
Confirmed that works! Thnx!

**Comment by spmallette** [comment]
glad that resolved your issue.  not sure what you are using rexster for, but please keep in mind that for TinkerPop3, Rexster is being replaced by Gremlin Server (though Gremlin Server will not have a UI):

http://tinkerpop.incubator.apache.org/docs/3.0.0.M9-incubating/#gremlin-server

If you are doing new development you might want to catch up on the latest developments there.

**Comment by earlonrails** [comment]
Yeah I am just trying to use rexster with orientdb, maybe I have to switch to gremlin server? I am getting this kind of stuff: 

```
[WARN] GraphConfigurationContainer - GraphConfiguration [com.tinkerpop.rexster.OrientGraphConfiguration] could not instantiate a class [com/orientechnologies/orient/core/OOrientListener].  Ensure that it is in Rexster's path.
com.tinkerpop.rexster.config.GraphConfigurationException: GraphConfiguration [com.tinkerpop.rexster.OrientGraphConfiguration] could not instantiate a class [com/orientechnologies/orient/core/OOrientListener].  Ensure that it is in Rexster's path.
	at com.tinkerpop.rexster.config.GraphConfigurationContainer.getGraphFromConfiguration(GraphConfigurationContainer.java:138)
	at com.tinkerpop.rexster.config.GraphConfigurationContainer.<init>(GraphConfigurationContainer.java:54)
	at com.tinkerpop.rexster.server.XmlRexsterApplication.reconfigure(XmlRexsterApplication.java:99)
	at com.tinkerpop.rexster.server.XmlRexsterApplication.<init>(XmlRexsterApplication.java:47)
	at com.tinkerpop.rexster.Application.<init>(Application.java:97)
	at com.tinkerpop.rexster.Application.main(Application.java:189)
```

I am not really trying to develop so I have now been using just the 2.5.0 download, which I should've maybe been using from the beginning. 

I am using orientdb 2.0.9 and trying to configure with this block 

```

        <graph>
          <graph-enabled>true</graph-enabled>
          <graph-name>dota_heroes</graph-name>
          <graph-type>com.tinkerpop.rexster.OrientGraphConfiguration</graph-type>
          <graph-location>plocal:/usr/local/Cellar/orientdb/2.0.9/libexec/databases/dota_heroes</graph-location>
          <properties>
            <username>root</username>
            <password>blah</password>
          </properties>
          <extensions>
            <allows>
              <allow>tp:gremlin</allow>
            </allows>
          </extensions>
        </graph>

```

Maybe I will try with the gremlin server thnx again! If there is another place where folks can chat like this a get help with configuring rexster and or graphdb's, like IRC would you happen to know the channel?

**Comment by spmallette** [comment]
OrientDB isn't shipped with Rexster so you have to include the appropriate jar files yourself.

http://orientdb.com/docs/last/Rexster.html

Make sure you copy in all the of the OrientDB jars (and dependencies) to Rexster's `ext` directory.  

OrientDB does not yet have a TinkerPop3 implementation (and thus no Gremlin Server support).  I believe the OrientDB folks will be building one as soon as TinkerPop3 reaches GA (expected to release in a few weeks).

**Comment by earlonrails** [comment]
Here are the jar files I am trying to include from orientdb libexec/lib folder:

```
~/Projects/rexster/rexster-server/target/rexster-server-2.5.0-standalone  🏄  \ls /usr/local/Cellar/orientdb/2.0.9/libexec/lib/
activation-1.1.jar			commons-beanutils-1.7.0.jar		gremlin-java-2.6.0.jar			jansi-1.5.jar				orientdb-client-2.0.9.jar		orientdb-tools-2.0.9.jar
annotations-1.3.2.jar			commons-beanutils-core-1.8.0.jar	groovy-1.8.9.jar			javassist-3.16.1-GA.jar			orientdb-core-2.0.9.jar			pipes-2.6.0.jar
antlr-2.7.7.jar				commons-collections-3.2.1.jar		hamcrest-core-1.1.jar			jettison-1.3.3.jar			orientdb-distributed-2.0.9.jar		snappy-java-1.1.0.1.jar
asm-3.2.jar				commons-configuration-1.6.jar		hazelcast-3.3.jar			jline-0.9.94.jar			orientdb-enterprise-2.0.9.jar		stax-api-1.0.1.jar
asm-analysis-3.2.jar			commons-digester-1.8.jar		hibernate-jpa-2.0-api-1.0.0.Final.jar	jna-4.0.0.jar				orientdb-etl-2.0.9.jar
asm-commons-3.2.jar			commons-lang-2.4.jar			hppc-0.6.0.jar				jna-platform-4.0.0.jar			orientdb-graphdb-2.0.9.jar
asm-tree-3.2.jar			commons-logging-1.1.1.jar		jackson-annotations-2.2.3.jar		junit-4.10.jar				orientdb-jdbc-2.0.9.jar
asm-util-3.2.jar			concurrentlinkedhashmap-lru-1.4.1.jar	jackson-core-2.2.3.jar			mail-1.4.jar				orientdb-object-2.0.9.jar
blueprints-core-2.6.0.jar		gremlin-groovy-2.6.0.jar		jackson-databind-2.2.3.jar		minimal-json-0.9.1.jar			orientdb-server-2.0.9.jar
```

Copying: 

```
 ~/Projects/rexster/rexster-server/target/rexster-server-2.5.0-standalone  🏄  cp /usr/local/Cellar/orientdb/2.0.9/libexec/lib/* ext/
```

Running : 

```
[WARN] GraphConfigurationContainer - GraphConfiguration could not be found or otherwise instantiated: [com.tinkerpop.rexster.OrientGraphConfiguration]. Ensure that it is in Rexster's path.
com.tinkerpop.rexster.config.GraphConfigurationException: GraphConfiguration could not be found or otherwise instantiated: [com.tinkerpop.rexster.OrientGraphConfiguration]. Ensure that it is in Rexster's path.
	at com.tinkerpop.rexster.config.GraphConfigurationContainer.getGraphFromConfiguration(GraphConfigurationContainer.java:142)
	at com.tinkerpop.rexster.config.GraphConfigurationContainer.<init>(GraphConfigurationContainer.java:54)
	at com.tinkerpop.rexster.server.XmlRexsterApplication.reconfigure(XmlRexsterApplication.java:99)
	at com.tinkerpop.rexster.server.XmlRexsterApplication.<init>(XmlRexsterApplication.java:47)
	at com.tinkerpop.rexster.Application.<init>(Application.java:97)
	at com.tinkerpop.rexster.Application.main(Application.java:189)
Caused by: com.tinkerpop.rexster.config.GraphConfigurationException: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/usr/local/Cellar/orientdb/2.0.9/libexec/databases/dota_heroes' with mode=rw
	at com.tinkerpop.rexster.OrientGraphConfiguration.configureGraphInstance(OrientGraphConfiguration.java:90)
	at com.tinkerpop.rexster.config.GraphConfigurationContainer.getGraphFromConfiguration(GraphConfigurationContainer.java:124)
	... 5 more
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/usr/local/Cellar/orientdb/2.0.9/libexec/databases/dota_heroes' with mode=rw
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:220)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:244)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate(OrientBaseGraph.java:1822)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:171)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:103)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:99)
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:96)
	at com.tinkerpop.rexster.OrientGraphConfiguration.configureGraphInstance(OrientGraphConfiguration.java:87)
	... 6 more
Caused by: com.orientechnologies.orient.core.exception.OSerializationException: Cannot load database's configuration. The database seems to be corrupted.
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.load(OStorageConfigurationSegment.java:84)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:166)
	... 13 more
Caused by: com.orientechnologies.common.concur.lock.OLockException: File '/usr/local/Cellar/orientdb/2.0.9/libexec/databases/dota_heroes/database.ocf' is locked by another process, maybe the database is in use by another process. Use the remote mode with a OrientDB server to allow multiple access to the same database.
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.lock(OAbstractFile.java:385)
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.openChannel(OAbstractFile.java:646)
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.open(OAbstractFile.java:144)
	at com.orientechnologies.orient.core.storage.impl.local.OSingleFileSegment.open(OSingleFileSegment.java:57)
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.load(OStorageConfigurationSegment.java:64)
	... 14 more
[WARN] GraphConfigurationContainer - com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/usr/local/Cellar/orientdb/2.0.9/libexec/databases/dota_heroes' with mode=rw
com.tinkerpop.rexster.config.GraphConfigurationException: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/usr/local/Cellar/orientdb/2.0.9/libexec/databases/dota_heroes' with mode=rw
	at com.tinkerpop.rexster.OrientGraphConfiguration.configureGraphInstance(OrientGraphConfiguration.java:90)
	at com.tinkerpop.rexster.config.GraphConfigurationContainer.getGraphFromConfiguration(GraphConfigurationContainer.java:124)
	at com.tinkerpop.rexster.config.GraphConfigurationContainer.<init>(GraphConfigurationContainer.java:54)
	at com.tinkerpop.rexster.server.XmlRexsterApplication.reconfigure(XmlRexsterApplication.java:99)
	at com.tinkerpop.rexster.server.XmlRexsterApplication.<init>(XmlRexsterApplication.java:47)
	at com.tinkerpop.rexster.Application.<init>(Application.java:97)
	at com.tinkerpop.rexster.Application.main(Application.java:189)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/usr/local/Cellar/orientdb/2.0.9/libexec/databases/dota_heroes' with mode=rw
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:220)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:244)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate(OrientBaseGraph.java:1822)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:171)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:103)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:99)
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:96)
	at com.tinkerpop.rexster.OrientGraphConfiguration.configureGraphInstance(OrientGraphConfiguration.java:87)
	... 6 more
Caused by: com.orientechnologies.orient.core.exception.OSerializationException: Cannot load database's configuration. The database seems to be corrupted.
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.load(OStorageConfigurationSegment.java:84)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:166)
	... 13 more
Caused by: com.orientechnologies.common.concur.lock.OLockException: File '/usr/local/Cellar/orientdb/2.0.9/libexec/databases/dota_heroes/database.ocf' is locked by another process, maybe the database is in use by another process. Use the remote mode with a OrientDB server to allow multiple access to the same database.
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.lock(OAbstractFile.java:385)
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.openChannel(OAbstractFile.java:646)
	at com.orientechnologies.orient.core.storage.fs.OAbstractFile.open(OAbstractFile.java:144)
	at com.orientechnologies.orient.core.storage.impl.local.OSingleFileSegment.open(OSingleFileSegment.java:57)
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.load(OStorageConfigurationSegment.java:64)
	... 14 more
```

**Comment by spmallette** [comment]
ok - that whole stack trace is more telling.  looks like you have the files in the right place, but you are getting an internal exception related to:

```text
.OStorageException: Cannot open local storage '/usr/local/Cellar/orientdb/2.0.9/libexec/databases/dota_heroes' with mode=rw
````

I don't know what that means as it is a OrientDB exception.  @lvca can you be of help on this one?

**Comment by earlonrails** [comment]
Ok something is wrong maybe with the version of orientdb I am using. 
I tried using jruby Pacer gem to access the data and I am getting a similar error.

```
require 'pacer'
require 'pacer-orient'

graph = Pacer.orient('local:/usr/local/Cellar/orientdb/2.0.9/libexec/databases/dota_heroes', {:username => 'root', :password => 'hidden'})
Java::ComOrientechnologiesOrientCoreException::ODatabaseException: Error on opening database 'local:/usr/local/Cellar/orientdb/2.0.9/libexec/databases/dota_heroes'
	from com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(com/orientechnologies/orient/core/db/document/ODatabaseDocumentTx.java:195)
	from com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(com/orientechnologies/orient/core/db/document/ODatabaseDocumentTx.java:161)
	from com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(com/tinkerpop/blueprints/impls/orient/OrientGraphFactory.java:125)
	from com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getDatabase(com/tinkerpop/blueprints/impls/orient/OrientGraphFactory.java:111)
	from com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(com/tinkerpop/blueprints/impls/orient/OrientGraphFactory.java:71)
	from java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:483)
	from RUBY.getTx(/Users/kkrauss/.rvm/gems/jruby-1.7.19@graph-bench/gems/pacer-orient-2.3.6-java/lib/pacer-orient/factory_container.rb:65)
	from RUBY.get(/Users/kkrauss/.rvm/gems/jruby-1.7.19@graph-bench/gems/pacer-orient-2.3.6-java/lib/pacer-orient/factory_container.rb:60)
	from RUBY.orient(/Users/kkrauss/.rvm/gems/jruby-1.7.19@graph-bench/gems/pacer-orient-2.3.6-java/lib/pacer-orient.rb:61)
	from org.jruby.RubyProc.call(org/jruby/RubyProc.java:271)
	from RUBY.reopen(/Users/kkrauss/.rvm/gems/jruby-1.7.19@graph-bench/gems/pacer-2.0.17-java/lib/pacer/graph/pacer_graph.rb:47)
	from RUBY.initialize(/Users/kkrauss/.rvm/gems/jruby-1.7.19@graph-bench/gems/pacer-2.0.17-java/lib/pacer/graph/pacer_graph.rb:24)
	from RUBY.orient(/Users/kkrauss/.rvm/gems/jruby-1.7.19@graph-bench/gems/pacer-orient-2.3.6-java/lib/pacer-orient.rb:67)
	from RUBY.evaluate((irb):10)
	from org.jruby.RubyKernel.eval(org/jruby/RubyKernel.java:1107)
	from org.jruby.RubyKernel.loop(org/jruby/RubyKernel.java:1507)
	from org.jruby.RubyKernel.catch(org/jruby/RubyKernel.java:1270)
	from org.jruby.RubyKernel.catch(org/jruby/RubyKernel.java:1270)
	from Users.kkrauss.$_dot_rvm.rubies.jruby_minus_1_dot_7_dot_19.bin.irb.(root)(/Users/kkrauss/.rvm/rubies/jruby-1.7.19/bin/irb:13)
	from Users.kkrauss.$_dot_rvm.rubies.jruby_minus_1_dot_7_dot_19.bin.irb.(root)(Users/kkrauss/$_dot_rvm/rubies/jruby_minus_1_dot_7_dot_19/bin//Users/kkrauss/.rvm/rubies/jruby-1.7.19/bin/irb:13)jruby-1.7.19 :011 >
```

Maybe need to open up something with them.
