### ISSUE TITLE
Rexster + OrientDB + BulbFlow - 500 error on get_all after delete

### ISSUE THREAD

**Issue by unovongalixor** [tinkerpop/rexster#392]
My calls to http://ip:8182/graphs/project1/indices/menu?value=menu&key=element_type work fine until I delete one of the nodes.

after that rexster is returning a 500 error on . In debug mode I see a NullPointerException:

[ERROR] JuliToLog4jHandler - The RuntimeException could not be mapped to a response, re-throwing to the HTTP container
java.lang.NullPointerException
	at com.tinkerpop.blueprints.util.io.graphson.GraphSONUtility.createPropertyMap(GraphSONUtility.java:637)
	at com.tinkerpop.blueprints.util.io.graphson.GraphSONUtility.objectNodeFromElement(GraphSONUtility.java:218)
	at com.tinkerpop.blueprints.util.io.graphson.GraphSONUtility.jsonFromElement(GraphSONUtility.java:198)
	at com.tinkerpop.blueprints.util.io.graphson.GraphSONUtility.jsonFromElement(GraphSONUtility.java:388)
	at com.tinkerpop.rexster.IndexResource.getElementsFromIndex(IndexResource.java:182)
	at com.tinkerpop.rexster.IndexResource.getElementsFromIndex(IndexResource.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

anyone had a similar issue withr exster and orientdb? If this continues i'll have to drop rexster and use the OrientDB api directly

**Comment by spmallette** [comment]
Can you please supply some curl commands that recreate the problem you're having?  That would be helpful...thanks.
